apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
  labels:
    app: task1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-volume-1
              mountPath: /tmp/input
        - name: busybox
          image: busybox:1.28-musl
          command: ['/bin/sh', '-c', 'while true; do echo "$(date) Hello from busybox!" > /tmp/output/welcome.txt; sleep 5; done']
          volumeMounts:
            - name: shared-volume-1
              mountPath: /tmp/output
      volumes:
        - name: shared-volume-1
          persistentVolumeClaim:
            claimName: shared-pv-1-claim
