apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  port.nginx: "80"
  port.multitool: "8080"
  welcome: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title></title>
    </head>
    <body>
      Hello from Kuber!
    </body>
    </html>
