apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.24-alpine
          ports:
            - containerPort: 80
              name: http-nginx-svc
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 8080
              name: mtool-nginx-svc
          env:
            - name: HTTP_PORT
              value: "8080"
