apiVersion: v1
kind: Service
metadata:
  name: nginx-out-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 9001
      targetPort: http-nginx-svc
      nodePort: 30080
    - name: mtool
      port: 9002
      targetPort: mtool-nginx-svc
      nodePort: 30081
