apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: nginx
      port: 9080
      targetPort: 80
      nodePort: 30080
    - name: mtool
      port: 9090
      targetPort: 8080
      nodePort: 30090
