apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-1
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/shared-volumes/volume-1
