apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-1.2
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/shared-volumes/volume-2
